package de.greenrobot.daoexample.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import de.greenrobot.dao.Match;
import de.greenrobot.dao.Member;

import de.greenrobot.daoexample.dao.MatchDao;
import de.greenrobot.daoexample.dao.MemberDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig matchDaoConfig;
    private final DaoConfig memberDaoConfig;

    private final MatchDao matchDao;
    private final MemberDao memberDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        matchDaoConfig = daoConfigMap.get(MatchDao.class).clone();
        matchDaoConfig.initIdentityScope(type);

        memberDaoConfig = daoConfigMap.get(MemberDao.class).clone();
        memberDaoConfig.initIdentityScope(type);

        matchDao = new MatchDao(matchDaoConfig, this);
        memberDao = new MemberDao(memberDaoConfig, this);

        registerDao(Match.class, matchDao);
        registerDao(Member.class, memberDao);
    }
    
    public void clear() {
        matchDaoConfig.getIdentityScope().clear();
        memberDaoConfig.getIdentityScope().clear();
    }

    public MatchDao getMatchDao() {
        return matchDao;
    }

    public MemberDao getMemberDao() {
        return memberDao;
    }

}
