package de.greenrobot.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
import java.io.Serializable;

import android.util.SparseArray;
// KEEP INCLUDES END
/**
 * Entity mapped to table MatchTable.
 */
public class Match implements Serializable{

    private Long id;
    /** Not-null value. */
    private java.util.Date time;
    /** Not-null value. */
    private String area;
    /** Not-null value. */
    private String manager;
    /** Not-null value. */
    private String members;
    private String paidMembers;
    private Integer price;
    private Boolean isComplete;

    // KEEP FIELDS - put your custom fields here
	private String membersString;
	private String dateString;
	private SparseArray<Member> membersList;//参与成员
	private SparseArray<Member> paidMembersList;//已缴费成员
    // KEEP FIELDS END

    public Match() {
    }

    public Match(Long id) {
        this.id = id;
    }

    public Match(Long id, java.util.Date time, String area, String manager, String members, String paidMembers, Integer price, Boolean isComplete) {
        this.id = id;
        this.time = time;
        this.area = area;
        this.manager = manager;
        this.members = members;
        this.paidMembers = paidMembers;
        this.price = price;
        this.isComplete = isComplete;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public java.util.Date getTime() {
        return time;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTime(java.util.Date time) {
        this.time = time;
    }

    /** Not-null value. */
    public String getArea() {
        return area;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setArea(String area) {
        this.area = area;
    }

    /** Not-null value. */
    public String getManager() {
        return manager;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setManager(String manager) {
        this.manager = manager;
    }

    /** Not-null value. */
    public String getMembers() {
        return members;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setMembers(String members) {
        this.members = members;
    }

    public String getPaidMembers() {
        return paidMembers;
    }

    public void setPaidMembers(String paidMembers) {
        this.paidMembers = paidMembers;
    }

    public Integer getPrice() {
        return price;
    }

    public void setPrice(Integer price) {
        this.price = price;
    }

    public Boolean getIsComplete() {
        return isComplete;
    }

    public void setIsComplete(Boolean isComplete) {
        this.isComplete = isComplete;
    }

    // KEEP METHODS - put your custom methods here
	public String getMembersString() {
		return membersString;
	}

	public void setMembersString(String membersString) {
		this.membersString = membersString;
	}

	public String getDateString() {
		return dateString;
	}

	public void setDateString(String dateString) {
		this.dateString = dateString;
	}

	public SparseArray<Member> getMembersList() {
		return membersList;
	}

	public void setMembersList(SparseArray<Member> menbersList) {
		this.membersList = menbersList;
	}

	public SparseArray<Member> getPaidMembersList() {
		return paidMembersList;
	}

	public void setPaidMembersList(SparseArray<Member> paidMembersList) {
		this.paidMembersList = paidMembersList;
	}
    // KEEP METHODS END

}
